import 'package:get/get.dart';

class Tr extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'zh': {
          'title': 'VRChat 配置',
          'cache': '缓存',
          'cache_dir': '缓存位置',
          'choose': '选择',
          'cache_size': '缓存大小',
          'clear': '清除',
          'cache_expiry': '缓存过期时间',
          'day': '天',
          'days': '天',
          'config_path': '配置文件路径',
          'config_not_found': '未找到配置文件',
          'enter': '输入',
          'edit': '修改',
          'move': '移动',
          'confirm': '确认',
          'cancel': '取消',
          'clear_cache': '清除缓存',
          'clear_cache_confirm': '确定要清除缓存吗？',
          'move_cache': '移动缓存',
          'move_cache_confirm': '是否移动缓存文件到新位置？',
          'copied': '已复制到剪贴板',
          'copy': '复制',
          'no_game': '游戏配置路径不存在',
        },
        'en': {
          'title': 'VRChat Configs',
          'cache': 'Cache',
          'cache_dir': 'Cache Location',
          'choose': 'Choose',
          'cache_size': 'Cache Size',
          'clear': 'Clear',
          'cache_expiry': 'Cache Expiry',
          'day': 'day',
          'days': 'days',
          'config_path': 'Config Path',
          'config_not_found': 'Config file not found',
          'enter': 'Enter',
          'edit': 'Edit',
          'move': 'Move',
          'confirm': 'Confirm',
          'cancel': 'Cancel',
          'clear_cache': 'Clear Cache',
          'clear_cache_confirm': 'Are you sure to clear cache?',
          'move_cache': 'Move Cache',
          'move_cache_confirm': 'Do you want to move cache to new location?',
          'copied': 'Copied to clipboard',
          'copy': 'Copy',
          'no_game': 'Game config path not found',
        }
      };
}
